### ISSUE TITLE
Wildcard certificates don't work

### ISSUE THREAD

**Issue by ghost** [TomCoreIO/TomCore.Tls#6]
Wildcard certificates cannot be imported into KeyVault:

at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
at Azure.Security.KeyVault.Certificates.CertificateClient.ImportCertificateAsync(ImportCertificateOptions importCertificateOptions, CancellationToken cancellationToken)
at TomCode.Tls.Functions.CertificateGeneration.AcmeCertificateGeneration.CreateCertificate(AcmeContext accountContext, CertificateOrderInfo orderInfo) in /src/CertificateGeneration/AcmeCertificateGeneration.cs:line 166
at TomCode.Tls.Functions.CertificateGeneration.AcmeCertificateGeneration.RunDnsChallenges(AcmeAccountData acmeAccountData, CertificateOrderInfo[] certificateOrderInfo) in /src/CertificateGeneration/AcmeCertificateGeneration.cs:line 97
Stack: at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
at Azure.Security.KeyVault.Certificates.CertificateClient.ImportCertificateAsync(ImportCertificateOptions importCertificateOptions, CancellationToken cancellationToken)
at TomCode.Tls.Functions.CertificateGeneration.AcmeCertificateGeneration.CreateCertificate(AcmeContext accountContext, CertificateOrderInfo orderInfo) in /src/CertificateGeneration/AcmeCertificateGeneration.cs:line 166
at TomCode.Tls.Functions.CertificateGeneration.AcmeCertificateGeneration.RunDnsChallenges(AcmeAccountData acmeAccountData, CertificateOrderInfo[] certificateOrderInfo) in /src/CertificateGeneration/AcmeCertificateGeneration.cs:line 97

**Comment by ghost** [comment]
Adapted name of the certificate being uploaded.
